# The name of the workflow.
#
name: Server CI/CD

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
      - name: create env file
        run: |
          cd server
          touch .env
          echo NODE_ENV = 'development' >> .env
          echo MONGO_URI = ${{secrets.MONGO_URI}} >> .env
      - name: build and test
        run: |
          cd server
          npm ci
          npm run build
          npm run test