# The name of the workflow.
#
name: Server CI/CD

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
      - run: |
          cd server
          npm ci
          npm run build
          npm run test
